export let categories = [
  "Advice Needed",
  "Asking For A Colleague",
  "Ask Me Anything",
  "Bluecollar Community",
  "Burning Issues",
  "Career Advice",
  "Changemaking",
  "Communities",
  "Company News",
  "Confessions",
  "Crazy Ideas",
  "Culture",
  "Customer Experience",
];
